name: app4
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    bloc: ^8.1.2 # state management
    flutter:
        sdk: flutter # flutter sdk
    flutter_bloc: ^8.1.3 # state management
    flutter_screenutil: ^5.9.0
    flutter_staggered_animations: ^1.1.1 # animation
    hive: ^2.2.3 # local database
    hive_flutter: ^1.1.0 # local database
    just_audio: ^0.9.34 # audio player
    just_audio_background: ^0.0.1-beta.10 # audio player background
    on_audio_query: ^2.9.0 # get songs from device
    package_info_plus: ^4.1.0 # get app info
    permission_handler: ^10.4.3 # get permission
    rxdart: ^0.27.7 # stream
    share_plus: ^7.1.0 # share song
    url_launcher: ^6.1.12 # open url
    riverpod_lint: ^2.3.7
    riverpod: ^2.4.9
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.2 # linter
    flutter_launcher_icons: ^0.13.1 # app icon generator
    build_runner: ^2.4.7
    custom_lint: ^0.5.7
    riverpod_generator: ^2.3.9
    riverpod_annotation: ^2.3.3
    flutter_riverpod: ^2.4.9

flutter:
    uses-material-design: true
    assets:
        - assets/icon/

flutter_launcher_icons:
    image_path: "assets/icon/icon.png"
    android: true
    ios: true